KidneyOS/KidneyOS

- .gdbinit
- .gitignore
- Makefile
This pull request makes it easier to debug the kernel with gdb. If you run `make run-qemu-gdb`, then run `rust-gdb` once qemu has started, you should be able to view source code, print locals, set breakpoints, etc.
> improve gdb debugging of kernel

- Makefile
- src/lib.rs
- src/mem/buddy_allocator.rs
This pull request fixes a memory leak in the buddy allocator unit test. It also fixes the `test` makefile target so it tests both the binary and library tests for the `kidneyos` crate.
Memory leaks are still possible in this unit test when the test fails, but that's probably fine.
> fix memory leak in buddy allocator unit test

- src/mem/mod.rs
- src/mem/pool_allocator.rs
Got the Pool Allocator's basic implementation done, as instructed and helped by @mtoohey31
Implementation details: 
- Now uses an allocation strategy that is similar to a file system allocation strategy (with blocks of fixed sizes and uses a bitmap to keep track of allocated / deallocated chunks). This is probably valid because we are assuming each block to be only of size `<N>` (parameter passed to Pool Allocator), and we will probably not call `PoolAllocator.allocate()` with some input that is not a multiple of size `N`. 
- Has a bunch of `unsafe` operations (I'm not quite sure how to fix this as I am working with a memory region, and I don't think Rust allows me to do stuff in those region without specifying `unsafe`)
Potential problems:
- Currently the space for the bitmap for the …
> Pool Allocator Implementation

- Makefile
Fixes an issue when building on MacOS ARM chips (due to `$(OBJCOPY)$`) by replacing the instances of it with `i686-unknown-linux-gnu-objcopy`.
> Fix Makefile Bug

- kernel/src/sync.rs
Utilizes the `pushfd` command over the `pushf` command to ensure that our stack pointer is moved by 4 bytes at a time. Uses the `popfd` command to properly restore the stack pointer.
> Hotfix: Properly restore stack pointer in ASM

- .github/workflows/ci.yaml
- .gitignore
- Makefile
- nix/flake.nix
- rust-toolchain.toml
This merge request adds targets for checking code coverage to our Makefile. It doesn't enforce any specific level of code coverage. I don't think aiming for a certain % makes sense since there are lots of things that we just can't do in tests (for example, anything that requires the CPU to be in kernel mode). I'll add instructions about how to use this to our mdbook documentation once either this or #21 is merged.
> Add code coverage targets

- kernel/src/user_program/elf_loader.rs
- kernel/src/user_program/virtual_memory_area.rs
The function validate_segment() is added, it is responsible for verifying that a segment described by a program header in an ELF file is valid and can be safely loaded into memory for execution.
> Add segment validation for each program header.

- kernel/Cargo.toml
- kernel/src/sync/intr.rs
- kernel/src/sync/mod.rs
- kernel/src/sync/mutex.rs
- kernel/src/sync/mutex/ticket.rs
- kernel/src/threading/context_switch.rs
- kernel/src/threading/mod.rs
- kernel/src/threading/scheduling/mod.rs
- kernel/src/threading/thread_functions.rs
`TicketMutex` grants the lock to the first thread that requested it. Also added `Mutex` providing an abstraction over the type of the mutex we use, which is enabled through a cfg directive.
> Add TicketMutex

- kernel/src/interrupt_descriptor_table.rs
- kernel/src/main.rs
- kernel/src/pic.rs
- kernel/src/sync/intr.rs
- kernel/src/sync/mutex/ticket.rs
- kernel/src/threading/context_switch.rs
- kernel/src/threading/mod.rs
- kernel/src/threading/scheduling/mod.rs
- kernel/src/threading/thread_control_block.rs
- kernel/src/threading/thread_functions.rs
- kernel/src/timer.rs
- kernel/src/user_program/syscall.rs
- shared/src/paging.rs
- shared/src/serial.rs
Enables timer interrupts by programming the PICs and PIT when initializing the OS. Uses this to implement a coarse system clock and a simple `sleep` (kernel) function.
> Enables timer interrupts and adds a system clock

- .gitignore
- kernel/src/main.rs
- kernel/src/sync/intr.rs
- kernel/src/sync/irq.rs
- kernel/src/sync/mod.rs
- kernel/src/sync/mutex.rs
- kernel/src/sync/mutex/ticket.rs
- kernel/src/threading/scheduling/mod.rs
- kernel/src/timer.rs
Adds `MutexIrq` and an interrupt guard so that the user doesn't have to disable the held guard and it'll drop when it falls out of scope.
> Add irq safe mutex and interrupts guard

- Makefile
On macOS, the system `ar` doesn't play nice with our provided `ar` command (not sure if that's a command syntax issue or  an architecture issue). We should use the cross-compile `ar` explicitly instead. Building with Docker + nix still works.
Apart from that, you can build on macOS by installing these dependencies:
```sh
brew tap messense/macos-cross-toolchains
brew install i686-unknown-linux-gnu
brew install objconv # Required to build by grub
brew install autoconf automake pkg-config # Unsure if needed but they are installed on my system.
brew install gawk # macOS awk doesn't work nicely with the grub install scripts
brew install xorriso # grub-mkrescue invokes this to create the ISO
echo "alias awk=gawk" >> ~/.zshrc
git clone git://git.savannah.gnu.org/grub.git
cd grub
./bootstrap # …
```
> Use cross compile ar instead of system

- shared/src/paging.rs
**Problem**: On startup, we panic when we're cleaning up our `PageManager` struct. Stack trace is below. This happens because we free a pointer (constructed via a table frame number in our page directory) that was not allocated via our block allocator (so `.deallocate` can't find a subblock allocator that works nicely with it).
This frame number was created via `huge_map`, which does not use the allocator (as opposed to `map`, which uses the allocator). The frame number for huge_maps I think points to the beginning of the 4MB section (instead of a page table), so it is not allocated (and does not need to be dealloc'd).
```
#0  kidneyos::mem::{impl#2}::dealloc (self=0x8016b008 <kidneyos::KERNEL_ALLOCATOR::h6a290f7483a3673f>, ptr=0x8148c000, layout=...) at kernel/src/mem/mod.rs:269
#1 …
```
> Proposal: Fixing internal inconsistency detected in kernel allocator with ptr 0x8148C000

- kernel/src/block/block_core.rs
- kernel/src/block/block_error.rs
- kernel/src/block/mod.rs
- kernel/src/drivers/dummy_device.rs
- kernel/src/drivers/mod.rs
- kernel/src/main.rs
The block layer for the file system. 
```rust
/// Register a block device with the given `name`. The block device's `size` in sectors and its
/// `device_type` must be prvided, as well as the `driver` to access the block.
///
/// Returns the index of the block device.
BlockManager::register_block(
&mut self,
block_type: BlockType,
block_name: &str,
block_size: BlockSector,
driver: BlockDriver,
) -> usize
```
```rust
/// Reads sector `sector` from the block device into `buf`, which must have room for
Block::read(&mut self, sector: BlockSector, buf: &mut [u8])
/// Writes sector `sector` from `buf`, which must contain `BLOCK_SECTOR_SIZE` bytes. Returns
/// after the block device has acknowledged receiving the data.
Block::write(&mut self, sector: BlockSector, buf: &[u8]) …
```
> File system block layer

- kernel/src/interrupts/idt.rs
- kernel/src/interrupts/intr_handler.rs
- kernel/src/interrupts/mod.rs
- kernel/src/interrupts/mutex_irq.rs
- kernel/src/interrupts/pic.rs
- kernel/src/interrupts/timer.rs
- kernel/src/main.rs
- kernel/src/sync/mod.rs
- kernel/src/threading/context_switch.rs
- kernel/src/threading/mod.rs
- kernel/src/threading/scheduling/mod.rs
- kernel/src/threading/thread_functions.rs
Currently, the code which setups and handles our interrupt flow is scattered around various files which aren't all named accordingly. This just refactors all the interrupt-related code into one module. This should also simplify interacting with it for people unfamiliar with the process system as there is now a clear place to setup interrupt handlers.
> Refactor interrupt-related code

- kernel/src/threading/mod.rs
- kernel/src/threading/process_table.rs
- kernel/src/threading/thread_control_block.rs
Creates the PCB when necessary and ownership of them is handed to a global `PROCESS_TABLE`.
> Add PCB functionality back

- kernel/src/main.rs
- kernel/src/mem/mod.rs
- kernel/src/mem/util.rs
- kernel/src/paging.rs
Add some functions so that we can access userspace pointers passed in from syscalls. Currently this is incomplete, since we need to check whether the pointers are actually mapped (e.g. on Linux at least, `open((void *)0x1234, 0)` returns `-EFAULT` rather than causing an interrupt). But it's good to at least have a version we can use for now.
Also I'm assuming we're following the Linux convention of pointers `>= 0x8000_0000` corresponding to kernel-space, but I'm not sure if that's true (seems to be as far as I can tell).
> Add some basic functions for accessing userspace pointers

- kernel/src/interrupts/intr_handler.rs
- syscalls.mk
I was getting really weird bugs and I think I tracked down the problem: interrupt handlers were overwriting register values in the middle of the program's execution.
(This instruction should be just executed once. But instead, we break on it the first time and see the correct register values, and then click "continue" and hit the breakpoint again, this time with random garbage register values)
If we look at [an interrupt handler from another operating system](https://github.com/cfenollosa/os-tutorial/blob/master/18-interrupts/cpu/interrupt.asm), they use `pusha`/`popa` to preserve the values of the registers across the interrupt.
(Also unrelatedly I added the syscalls lib.rs to the syscall lib dependencies, because otherwise the syscalls library doesn't get rebuilt when lib.rs is …
> Push registers before handling interrupts

- .cargo/config.toml
- syscalls/.cargo/config.toml
Rust likes to generate SSE instructions for 64-bit loads/stores, which leads to an invalid instruction exception, since qemu i386 system doesn't support SSE.
> Disable SSE instructions

- kernel/src/sync/mod.rs
- kernel/src/sync/mutex/sleep.rs
- kernel/src/threading/thread_control_block.rs
Currently SleepMutex isn't very useful, since its lock method requires `&mut self`, and you can't have multiple mutable references at once to a value in Rust.
We can make `SleepMutex` take `&self` (as `std::sync::Mutex` does) by making the `holding_thread` atomic and using a `MutexIrq` to store the wait queue.
I have removed `force_unlock`, since `std::sync::Mutex` doesn't even have it (but lmk if you want to add it back in).
> Make `SleepMutex::lock` take `&self`

- shared/src/video_memory.rs
> **Note:** The linter suggested using an iterator, so I tried the following:
> ```rust
>                 for char in video_memory.iter_mut().take(end).skip(start) {
>                     *char = Character {
>                         ascii: b' ',
>                         attribute: self.attribute,
>                     };
>                 }
> ```
> However, this didn't work as expected. Could someone suggest a fix?
Fix the issue in the `VideoMemoryWriter` where residual characters remain on the screen after scrolling.
> Fix Residual Characters when Scrolling in VideoMemoryWriter

- kernel/src/interrupts/mutex_irq.rs
- kernel/src/main.rs
- kernel/src/sync/mod.rs
- kernel/src/sync/mutex.rs
- kernel/src/sync/mutex/sleep.rs
- kernel/src/sync/mutex/ticket.rs
- kernel/src/sync/rwlock/mod.rs
- kernel/src/sync/rwlock/sleep.rs
- kernel/src/system.rs
Add an RwLock structure, similar to `std::sync::RwLock`.
I've tested out this implementation with 10000 threads on my machine and it seems to work fine.
This PR also removes `force_unlock` since clippy was complaining about it and we're not using it anymore (std's mutex doesn't have it so I think it's fine if we don't— forcibly unlocking a mutex is almost always a bad idea...)
> Implement RwLock

- .githooks/pre-commit
- Makefile
- kernel/src/block/block_error.rs
- kernel/src/block/partitions/mod.rs
- kernel/src/block/partitions/partition_core.rs
- kernel/src/block/partitions/partition_register.rs
- kernel/src/block/partitions/partition_utils.rs
The new disk image contains a swap partition from sector 2048 to 10240 (8192 sectors).
To mount/unmount the ext4 partition
```sh
cd KidneyOS
sudo losetup -o $[10240*512] /dev/loop0 mbr_ext4_50MiB.img
sudo losetup -a
sudo mount /dev/loop0 /mnt/sub/dir
sudo umount /dev/loop0
sudo losetup -d /dev/loop0
sudo losetup -a  # should report nothing
```
> Register Swap Partition

- Cargo.lock
- Cargo.toml
- kernel/Cargo.toml
- kernel/src/block/block_core.rs
- kernel/src/block/partitions/partition_core.rs
- kernel/src/drivers/ata/ata_core.rs
- kernel/src/fs/fs_manager.rs
- kernel/src/fs/mod.rs
- kernel/src/fs/syscalls.rs
- kernel/src/main.rs
- kernel/src/sync/mutex/sleep.rs
- kernel/src/sync/mutex/ticket.rs
- kernel/src/system.rs
- kernel/src/threading/context_switch.rs
- kernel/src/threading/mod.rs
- kernel/src/threading/process.rs
- kernel/src/threading/scheduling/mod.rs
- kernel/src/threading/thread_control_block.rs
- kernel/src/threading/thread_functions.rs
- kernel/src/threading/thread_sleep.rs
- kernel/src/user_program/syscall.rs
- shared/src/mem/mod.rs
- shared/src/paging.rs
Resolves #87 
With this PR, you can only access SystemState through a shared reference. The members of SystemState have to manage shared access individually.
We still have to use a `static mut` for the SystemState, but it's now private and can only be accessed through safe functions (an atomic variable is used to keep track of whether the systesm is initialized). I wanted to use the `once_cell` crate, but it looks like that needs either std or critical-section, and critical-section wasn't working …
Also I've moved the `RootFileSystem` object to SystemState, now that it can be accessed safely there 
~~(Currently a draft until #100 is merged)~~
> Accessing SystemState safely

- Makefile
- kernel/src/main.rs
- kernel/src/threading/thread_control_block.rs
- kernel/src/threading/thread_functions.rs
We have an interpretation problem for our `eip` variable in our TCB struct. There are two cases:
- If pid == 0, this thread is considered a kernel thread, and `eip` is the pointer to be a **pointer to a pointer** to the entry of the thread.
- If pid != 0, this thread is considered a user thread, and `eip` is considered to be a **pointer** to the entry of the thread.
This PR decouples these behaviours and avoids some crashes with multiple TCBs.
> Don't use indirect EIP for TCB

- kernel/src/threading/context_switch.rs
- kernel/src/threading/thread_functions.rs
The implementation of the process_exit function was not properly disposing of non-running child threads of the current process. This hasn't resulted in any issues yet as there is currently no multi-threadding support and the last running child is disposed of properly.
> Fix issue with exited process not properly dropping threads

- .github/workflows/ci.yaml
- kernel/src/main.rs
- kernel/src/threading/mod.rs
- kernel/src/threading/thread_control_block.rs
- kernel/src/user_program/syscall.rs
- programs/execve/src/main.rs
- scripts/generate-disk.bash
- syscalls/include/kidneyos.h
- syscalls/src/defs.rs
- syscalls/src/lib.rs
The `execve` syscall now uses the disk! Hooray!
`argv` and `envp` are ignored.
> Read execve executable from disk

- kernel/src/fs/fs_manager.rs
- kernel/src/interrupts/idt.rs
- kernel/src/interrupts/intr_handler.rs
- kernel/src/main.rs
- kernel/src/mem/mod.rs
- kernel/src/mem/vma.rs
- kernel/src/threading/thread_control_block.rs
- shared/src/paging.rs
Currently the only VMA is the stack, which is now allocated on-demand rather than all at once when the process is created.
The stack physical memory isn't freed on process exit yet, but it looks like that wasn't happening before, so at least it's not a regression.
> Add support for VMAs
